"""OBS bridge helper — translates MIDI from "Universal Controller MIDI" into
obs-websocket calls.

Prereqs:
    pip install obsws-python==1.6.* python-rtmidi==1.5.*

Run:
    python obs_bridge_helper.py --password YOUR_OBS_PASSWORD

This file is generated by the Universal Controller MIDI OBS connector and dropped
into ~/Documents/Universal Controller MIDI (OBS)/. Edit the ACTIONS dict to change
bindings without re-installing.
"""
from __future__ import annotations

import argparse
import logging
import sys
from typing import Optional

try:
    import rtmidi  # type: ignore
    from obsws_python import ReqClient  # type: ignore
except ImportError as e:
    print(f"Missing dependency: {e}")
    print("Install with:")
    print("    pip install obsws-python==1.6.* python-rtmidi==1.5.*")
    sys.exit(1)


# Note number -> (action_name, *args). Edit me!
# Default mapping uses Universal Controller MIDI defaults: face buttons 60-65,
# shoulders 67/69, d-pad 78-81.
ACTIONS = {
    60: ("scene", 0),
    62: ("scene", 1),
    64: ("scene", 2),
    65: ("scene", 3),
    67: ("toggle_first_source",),
    69: ("toggle_first_source",),
    78: ("mute_audio", True),    # D-pad up — mute
    79: ("mute_audio", False),   # D-pad down — unmute
    80: ("prev_scene",),         # D-pad left
    81: ("next_scene",),         # D-pad right
}


log = logging.getLogger("obs-bridge")


def _route_note(client: "ReqClient", note: int) -> None:
    if note not in ACTIONS:
        return
    action = ACTIONS[note]
    name = action[0]
    args = action[1:]
    try:
        if name == "scene":
            scenes = client.get_scene_list().scenes
            if len(scenes) > args[0]:
                client.set_current_program_scene(scenes[args[0]]["sceneName"])
        elif name == "prev_scene":
            client.trigger_studio_mode_transition()
        elif name == "next_scene":
            scenes = client.get_scene_list().scenes
            current = client.get_current_program_scene().scene_name
            idx = next((i for i, s in enumerate(scenes)
                        if s["sceneName"] == current), -1)
            if idx >= 0 and idx + 1 < len(scenes):
                client.set_current_program_scene(scenes[idx + 1]["sceneName"])
        elif name == "toggle_first_source":
            scene = client.get_current_program_scene().scene_name
            items = client.get_scene_item_list(scene).scene_items
            if items:
                item_id = items[0]["sceneItemId"]
                enabled = items[0]["sceneItemEnabled"]
                client.set_scene_item_enabled(scene, item_id, not enabled)
        elif name == "mute_audio":
            inputs = client.get_input_list().inputs
            for inp in inputs:
                if "kind" in inp and "audio" in inp.get("inputKind", ""):
                    client.set_input_mute(inp["inputName"], bool(args[0]))
                    break
    except Exception as e:
        log.warning("action %s failed: %s", name, e)


def main() -> int:
    parser = argparse.ArgumentParser(description="Universal Controller MIDI → OBS helper")
    parser.add_argument("--password", required=True, help="obs-websocket password")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=4455)
    parser.add_argument("--midi-port", default="Universal Controller MIDI")
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s | %(message)s",
    )

    client = ReqClient(host=args.host, port=args.port, password=args.password)
    log.info("Connected to OBS at %s:%d", args.host, args.port)

    midi_in = rtmidi.MidiIn()
    port_idx = _find_port(midi_in, args.midi_port)
    if port_idx is None:
        log.error("No MIDI port matching '%s'. Available: %s",
                  args.midi_port, midi_in.get_ports())
        return 1
    midi_in.open_port(port_idx)
    log.info("Listening on MIDI port: %s", midi_in.get_ports()[port_idx])

    def on_midi(event: tuple, _data: Optional[object] = None) -> None:
        message, _ = event
        if not message:
            return
        status = message[0] & 0xF0
        if status == 0x90 and len(message) >= 3 and message[2] > 0:
            _route_note(client, message[1])

    midi_in.set_callback(on_midi)
    log.info("Helper running. Ctrl+C to stop.")
    try:
        while True:
            import time
            time.sleep(1)
    except KeyboardInterrupt:
        log.info("Stopping.")
    finally:
        midi_in.close_port()
        del midi_in
    return 0


def _find_port(midi_in: "rtmidi.MidiIn", needle: str) -> Optional[int]:
    needle_lc = needle.lower()
    for i, name in enumerate(midi_in.get_ports()):
        if needle_lc in name.lower():
            return i
    return None


if __name__ == "__main__":
    sys.exit(main())
